name: Conditional Deploy

on:
  push:
    branches:
      - Dev
      - QA
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: show branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}       
      
      - name: run according to the branch name
        if: steps.extract_branch.outputs.branch  == 'Dev'
        run: echo 'from Dev'
        if:  steps.extract_branch.outputs.branch == 'QA'
        run: echo 'from QA'
