name: Conditional Deploy

on:
  push:
    branches:
      - Dev
      - QA
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}    
        
